spring.application.name=springbootweb

spring.datasource.url=jdbc:h2:file:/Users/Sanje/OneDrive/Desktop/springBoot/employeeDB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sanjeetDB
spring.datasource.password=Sanjeet@123
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console